"""add_vlm_model

Revision ID: 013f124caf70
Revises: 27dda7dc1d47
Create Date: 2026-06-13 06:31:28.331919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013f124caf70'
down_revision: Union[str, None] = '27dda7dc1d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config', sa.Column('vlm_model', sa.String(), nullable=True, comment='For image reconstruction'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_config', 'vlm_model')
    # ### end Alembic commands ###
