"""v107_fields

Revision ID: 27dda7dc1d47
Revises: 43e61d7dd24d
Create Date: 2026-06-12 23:00:21.758114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27dda7dc1d47'
down_revision: Union[str, None] = '43e61d7dd24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_config', 'enable_toc_removal',
               existing_type=sa.BOOLEAN(),
               comment='⚠️ deprecated since v1.0.3',
               existing_comment='deprecated since v1.0.3',
               existing_nullable=True)
    op.alter_column('app_config', 'enable_reference_removal',
               existing_type=sa.BOOLEAN(),
               comment='⚠️ deprecated since v1.0.3',
               existing_comment='deprecated since v1.0.3',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_config', 'enable_reference_removal',
               existing_type=sa.BOOLEAN(),
               comment='deprecated since v1.0.3',
               existing_comment='⚠️ deprecated since v1.0.3',
               existing_nullable=True)
    op.alter_column('app_config', 'enable_toc_removal',
               existing_type=sa.BOOLEAN(),
               comment='deprecated since v1.0.3',
               existing_comment='⚠️ deprecated since v1.0.3',
               existing_nullable=True)
    # ### end Alembic commands ###
