"""add_mineru_options

Revision ID: 40e4e2c7bcd2
Revises: 08396e620f25
Create Date: 2026-06-13 18:33:05.585647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40e4e2c7bcd2'
down_revision: Union[str, None] = '08396e620f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config', sa.Column('mineru_options', sa.JSON(), nullable=True, comment='MinerU execution options'))
    op.alter_column('app_config', 'docling_options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='⚠️ deprecated since v1.1.0',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('app_config', 'docling_options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='⚠️ deprecated since v1.1.0',
               existing_nullable=True)
    op.drop_column('app_config', 'mineru_options')
    # ### end Alembic commands ###
