"""init_db

Revision ID: 43e61d7dd24d
Revises: 
Create Date: 2026-06-12 22:37:42.383216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e61d7dd24d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('llm_base_url', sa.String(), nullable=True),
    sa.Column('llm_api_key_encrypted', sa.String(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('llm_context_window', sa.Integer(), nullable=True),
    sa.Column('llm_chunk_max_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_chunk_concurrency', sa.Integer(), nullable=True),
    sa.Column('llm_chunk_overlap_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_cleanup_aggressiveness', sa.String(), nullable=True),
    sa.Column('use_vlm_image_reconstruction', sa.Boolean(), nullable=True),
    sa.Column('keep_original_images', sa.Boolean(), nullable=True),
    sa.Column('enable_toc_removal', sa.Boolean(), nullable=True, comment='deprecated since v1.0.3'),
    sa.Column('enable_reference_removal', sa.Boolean(), nullable=True, comment='deprecated since v1.0.3'),
    sa.Column('enable_header_footer_removal', sa.Boolean(), nullable=True),
    sa.Column('enable_whitespace_cleanup', sa.Boolean(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('ocr_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('docling_options', sa.JSON(), nullable=True),
    sa.Column('storage_retention_days', sa.Integer(), nullable=True),
    sa.Column('disk_free_min_gb', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_filename', sa.String(), nullable=False),
    sa.Column('input_format', sa.String(), nullable=False),
    sa.Column('input_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_input_path', sa.String(), nullable=False),
    sa.Column('storage_output_path', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('progress_stage', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('jobs')
    op.drop_table('app_config')
    # ### end Alembic commands ###
